platform:ios, "11.0"
use_frameworks!
inhibit_all_warnings!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      config.build_settings['ENABLE_BITCODE'] ='NO'
    end
  end
end
def shared_pods

	pod 'AFNetworking'
	pod 'SDWebImage'
	pod 'Masonry'
	pod 'MJRefresh'
	pod 'YYKit'
	pod 'ReactiveObjC'
	pod 'Bugly'
	pod "Qiniu"
  pod 'IQKeyboardManager'
  pod 'DZNEmptyDataSet'
  pod 'Toast'
  pod 'AliyunOSSiOS'
  pod 'TZImagePickerController'
  pod 'UMCCommon'
  pod 'UMCShare/Social/WeChat'
  pod 'GTSDK'
  pod 'CocoaLumberjack' , '3.6.0'
  pod 'SVProgressHUD' , '2.2.5'
  pod 'DoraemonKit/Core', :configurations => ['Debug']
  pod 'DoraemonKit/WithGPS', :configurations => ['Debug']
  pod 'DoraemonKit/WithLoad', :configurations => ['Debug']
  pod 'DoraemonKit/WithDatabase', :configurations => ['Debug']
  pod 'DoraemonKit/WithMLeaksFinder', :configurations => ['Debug']
end
target 'iOSMain_dev' do
	shared_pods
end

target 'iOSMain_release' do
	shared_pods
end
